development:
  adapter: postgresql
  encoding: unicode
  database: fritter
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: fritter
  pool: 5
  username:
  password:
  host: localhost
